### PR TITLE
Raise upper bound on doctest dependency

### PR DESCRIPTION
**Pull request by chris-martin**

### CODE REVIEW

**Comment by nikita-volkov** [comment]
The CI tests are failing :(

**Comment by chris-martin** [comment]
Hm, I'm puzzled. `cabal new-test` and `stack test` are running the tests fine locally for me. I'm not really sure what's going on in the Travis setup?

**Comment by nikita-volkov** [comment]
It's done. Resolved with the new cool Cabal Doctest feature!

**Comment by chris-martin** [comment]
Oh, cool indeed! Thanks for looking into this.

**Pull request merged**
